module/Olcs/config/module.config.php
module/Olcs/config/routes.config.php
module/Olcs/src/Controller/Factory/Messages/LicenceCloseConversationControllerFactory.php
module/Olcs/src/Controller/Factory/Messages/LicenceConversationMessagesControllerFactory.php
module/Olcs/src/Controller/Messages/LicenceCloseConversationController.php
module/Olcs/src/Controller/Messages/LicenceConversationMessagesController.php
module/Olcs/src/Form/Model/Fieldset/CloseConversationActions.php
module/Olcs/src/Form/Model/Fieldset/CloseConversationText.php
module/Olcs/src/Form/Model/Form/CloseConversation.php
module/Olcs/src/Table/Tables/messages-list.table.php

This ticket is to allow the case worker to close the conversation and the user can no longer send a reply.
The command handler should close the existing conversation and mark the records on the database as closed.
The message will appear on the message tab as a closed conversation
Related issue: [VOL-4689](https://dvsa.atlassian.net/browse/VOL-4689)

feat: Close Conversation Front-end

---

public/index.php

Restore the setting of default locale.
This _should_ be set on the server running the code in the `ini` but this is easier and can be removed once the VOL application moves to containers.

fix: restore default locale

---

module/Olcs/src/Form/Model/Fieldset/EnvironmentalComplaint.php
module/Olcs/src/Form/Model/Fieldset/OppositionFields.php

Fix incorrect slashes in FQCN causing Add Oppostion form not to work.
https://dvsa.atlassian.net/browse/VOL-4848

fix: fix modal form while adding cases opposition page

---

module/Olcs/src/Form/Model/Fieldset/PublicInquiryHearingFields.php
module/Olcs/src/Form/Model/Fieldset/PublicInquiryRegisterDecisionMain.php
module/Olcs/src/Form/Model/Fieldset/PublicInquiryRegisterTmDecision.php

Removes the prepended slash from `service_name` in `Form\Options`.
Related issue: https://dvsa.atlassian.net/browse/VOL-4864

fix: remove slash from `service_name` in `Form\Options`

---

composer.lock

Bump `olcs-common` to `5.0.0-beta.3`

chore: bump `olcs-common` to `5.0.0-beta.3`

---

composer.lock

Bump `olcs-transfer` to `5.0.0-beta.8`.

chore: bump `olcs-transfer` to `5.0.0-beta.8`

---

composer.json
composer.lock

Laminas Form had an [issue](https://github.com/laminas/laminas-form/commit/733ea7eda2689147a6b2f7ad86d00133eea1f421) that was resolved only in v3.9.0 onwards. We use Laminas Form v3.4.x due to PHP version constraints. The fork that this now points to simply cherry-picks that commit until a point we can point back to the latest Laminas form version (PHP upgrade epic).
Related issue: https://dvsa.atlassian.net/browse/VOL-4871

fix: replace `laminas-form` with patched fork

---

composer.lock

Bump `olcs-common` to `5.0.0-beta.4`

chore: bump `olcs-common` to `5.0.0-beta.4`

---

module/Olcs/src/Controller/AbstractController.php
module/Olcs/src/Controller/Licence/Processing/LicenceProcessingTasksController.php

The view was trying to retrieve table filters from two different placeholder instances.
Related issue: https://dvsa.atlassian.net/browse/VOL-4897

fix: fix visibility of table filters

---

module/Olcs/src/Listener/RouteParam/Conversation.php

Locally you can use strong types here to get container items. In dev this resulted in a fatal error and white screen. Unblocker for now until a nicer strongly typed resolution can be added.

fix: Non local white screens when using strong types for the container

---

module/Admin/src/Controller/TaskAllocationRulesControllerFactory.php
module/Admin/src/Controller/TeamControllerFactory.php
module/Olcs/src/Controller/Application/Processing/ApplicationProcessingInspectionRequestControllerFactory.php
module/Olcs/src/Controller/Licence/Processing/LicenceProcessingInspectionRequestControllerFactory.php
module/Olcs/src/Controller/Operator/OperatorLicencesApplicationsControllerFactory.php

Fixes some errors from moving duped Data Services to correct plugin namespace

fix: missed dataservices from dedupe

---

module/Olcs/src/View/Helper/SubmissionSectionMultipleTablesFactory.php
test/Olcs/src/View/Helper/SubmissionSectionMultipleTablesFactoryTest.php

Replace old string alias being used in factory with suitable fqcn for translation service.
Related issue: [4927](https://dvsa.atlassian.net/browse/VOL-4927)

fix: Update factory trying unresolveable translator.

---

module/Olcs/src/Form/Model/Fieldset/CreateFeeDetails.php

Add `create_empty_option` to the `createdDate` for the create fee form so that the Laminas element returns `null` instead of `0000-00-00`.
Related issue: https://dvsa.atlassian.net/browse/VOL-4923

fix: add `create_empty_option` to `CreateFeeDetails`

---

module/Olcs/src/Controller/AbstractInternalController.php

Most of the Laminas collections (lists) have gone from LIFO to FIFO. So as this worked before as it was the last to get injected into the EventManager. It's no longer the case on Laminas v3 hence why an explicit priority above the Laminas `DispatchListener`.
Related issue: https://dvsa.atlassian.net/browse/VOL-4925

fix: tweak `CrudListener` priority to run before `DispatchListener`

---

module/Olcs/config/module.config.php
module/Olcs/src/Controller/Messages/AbstractCreateConversationController.php

Fix listeners for Create Conversation controllers
Related issue: [VOL-4681](https://dvsa.atlassian.net/browse/VOL-4681)

fix: Listeners for Create Conversation controllers

---

module/Olcs/src/Form/Model/Fieldset/BusServiceNumberAndType.php

Add `priority` to bus details form to fix ordering.
Related issue: https://dvsa.atlassian.net/browse/VOL-4942

fix: add `priority` to fix ordering of bus details form

---

module/Olcs/view/sections/cases/pages/appeals-stays.phtml

Refactor the undefined DB date constants.
Related issue: https://dvsa.atlassian.net/browse/VOL-4938

fix: fix undefined constant reference

---

module/Olcs/src/Controller/AbstractInternalController.php

Add `contentTitle` to placeholder to restore the old modal titles.
Related issue: https://dvsa.atlassian.net/browse/VOL-4941

fix: restore modal titles in confirmation modals

---

module/Olcs/config/module.config.php
module/Olcs/src/Service/Data/AbstractPublicInquiryDataServicesFactory.php
module/Olcs/src/Service/Data/ImpoundingLegislationFactory.php
module/Olcs/src/Service/Data/LicenceDecisionLegislationFactory.php

fix to inject correct Licence Data Service - resolves context issues when calling Reason list DTO.
Related issue: [VOL-4934](https://dvsa.atlassian.net/browse/VOL-4934)

fix: fix legislation data service dependency issues

---

module/Admin/src/Table/Tables/admin-irhp-permit-print.table.php

Table fixes causing IRHP permit print errors
Related issue: [VOL-4947](https://dvsa.atlassian.net/browse/VOL-4947)

Irhp permit printing formatter bug vol 4947

---

module/Admin/src/Controller/PermitsReportController.php

The method can (and does) return `Response|ViewModel`, though this cannot be represented in return types in PHP 7.4 so needs to be removed.
Related issue: https://dvsa.atlassian.net/browse/VOL-4958

fix: fix `TypeError` in `PermitsReportController`

---

module/Olcs/config/module.config.php

Missing factory mapping for the `VariationSchedule41Controller`.
Related issue: https://dvsa.atlassian.net/browse/VOL-4952

fix: add `VariationSchedule41Controller` factory mapping to service manager

---

module/Olcs/src/Controller/Messages/ApplicationConversationListController.php
module/Olcs/src/Controller/Messages/ApplicationConversationMessagesController.php
module/Olcs/src/Controller/Messages/ApplicationCreateConversationController.php
module/Olcs/src/Controller/Messages/LicenceConversationListController.php
module/Olcs/src/Controller/Messages/LicenceConversationMessagesController.php
module/Olcs/src/Controller/Messages/LicenceCreateConversationController.php

… pages
Add interfaces to add the licence/application header and sidebars to a few messaging pages where it was missing.
Related issue: [VOL-4921](https://dvsa.atlassian.net/browse/VOL-4921)

fix: Add missing licence (and application) headers to a few messaging pages

---

module/Olcs/view/partials/head.phtml

There was discrepancy in the favicon paths between `olcs-selfserve` and `olcs-internal`:
olcs-selfserve: `/static/public/assets/images/favicon.ico`
olcs-internal: `/static/public/images/bitmap/favicon.ico`
To ensure consistency and simplify maintenance, aligned the favicon path in `olcs-internal` with `olcs-selfserve`. 
This way, any changes made to olcs-static will automatically apply to both projects.
Related issue: [JIRA_TICKET_NUMBER](LINK_TO_JIRA_TICKET)

refactor:  Changed favicon path to align with olcs-selfserve.

---

module/Olcs/src/Controller/Messages/AbstractConversationMessagesController.php
module/Olcs/src/Form/Model/Fieldset/LicenceMessageReply.php
module/Olcs/view/pages/conversation/messages.phtml

Improve error message on invalid reply.
Related issue: [VOL-5075](https://dvsa.atlassian.net/browse/VOL-5075)

feat: Nicer error message on reply form with auto expand on error.

---

composer.lock
module/Olcs/src/Controller/Messages/AbstractConversationMessagesController.php

Add a footer to internal to show the first operator to read the message.
Related issue: [VOL-5082](https://dvsa.atlassian.net/browse/VOL-5082)

feat: Message footer showing operator first read

---

composer.json
composer.lock
config/autoload/config.global.php
module/Olcs/config/submission/submission.config.php
module/Olcs/src/Controller/AbstractInternalController.php
module/Olcs/src/Controller/Auth/LoginController.php
module/Olcs/src/Controller/Auth/LoginControllerFactory.php
module/Olcs/src/Controller/Cases/Submission/SubmissionController.php
module/Olcs/src/Controller/Licence/LicenceController.php
module/Olcs/src/Controller/Lva/Licence/TransportManagersController.php
module/Olcs/src/Controller/TransportManager/TransportManagerController.php
test/Admin/src/Data/Mapper/DataRetentionAssignTest.php
test/Admin/src/Listener/RouteParam/IrhpPermitAdminFurnitureTest.php
test/Admin/src/Navigation/UserDetailsNavigationFactoryTest.php
test/Olcs/src/Controller/Auth/LoginControllerFactoryTest.php
test/Olcs/src/Controller/Auth/LoginControllerTest.php
test/Olcs/src/Util/XhProf.php

Removes OpenAM Logic from repos.
Related issue: [VOL-2661](https://dvsa.atlassian.net/browse/VOL-2661)

refactor: remove OpenAM logic

---

module/Olcs/src/Controller/Messages/AbstractConversationListController.php

Pagination issue when using messages status filter
Related issue: [VOL-5178](https://dvsa.atlassian.net/browse/VOL-5178)

fix: Reset pagination when filtering conversations based on status

---

module/Admin/assets/js/inline/forms/translation-key-modal.js
phpcs.xml.dist

Unable to add or edit translation key due to form error due to rendering raw HTML
Related issue: [VOL-5198](https://dvsa.atlassian.net/browse/VOL-5198)

fix: Translation popup showing HTML rather then rendering

---

composer.lock

Bump olcs-transfer dep to 6.8.0

chore: Bump olcs-transfer dependency to 6.8.0

---

composer.lock
module/Olcs/src/Controller/SearchController.php

Allow further filtering of TM's in search
Related issue: [VOL-5211](https://dvsa.atlassian.net/browse/VOL-5211)

feat: TM search filter by app/licence

---

module/Olcs/src/Controller/SearchController.php

Search does not work on several licence pages as it overrides the :action variable with invalid actions on the controller.
Related issue: [VOL-5307](https://dvsa.atlassian.net/browse/VOL-5307)

fix: Search link does not work on several pages

---

module/Admin/src/Form/Model/Fieldset/FeeRateDetails.php
module/Admin/src/Form/Model/Fieldset/UserLoginSecurity.php
module/Olcs/src/Form/Model/Fieldset/CreatePermit.php
module/Olcs/src/Form/Model/Fieldset/IrhpApplication/Top.php
module/Olcs/src/Form/Model/Fieldset/IrhpBilateral/Top.php
module/Olcs/src/Form/Model/Fieldset/OperatorId.php
module/Olcs/src/Form/Model/Fieldset/TransportManagerDetails.php

Updates name of some elements renamed in php8 upgrade.
Related issue: [VOL-5435](https://dvsa.atlassian.net/browse/VOL-5435)

fix: Fixes some Readonly form elements that were not renamed in upgrade

---

composer.json
composer.lock

Removed the dependence on our Laminas Form fork. The only practical difference from this is a bump from 3.19.1 to 3.19.2
Related issue: [VOL-5402](https://dvsa.atlassian.net/browse/VOL-5402)

chore: VOL-5402 remove reliance on forked laminas-form package bump to 3.19.2

---

module/Olcs/view/sections/cases/pages/submission.phtml

While this fixed the original issue, if `selectedSectionsArray` was `null` it threw a TypeError once it got to `array_key_exists`.
Related issue: https://dvsa.atlassian.net/browse/VOL-5438

fix: fix TypeError when `selectedSectionsArray` is `null`

---

module/Olcs/src/Controller/Cases/PublicInquiry/HearingController.php
module/Olcs/src/Form/Model/Fieldset/ImpoundingFields.php
module/Olcs/src/Form/Model/Fieldset/NonPiFields.php
module/Olcs/src/Form/Model/Fieldset/PublicInquiryHearingFields.php
module/Olcs/src/Form/Model/Fieldset/PublicInquirySlaMain.php

Latest Laminas Form no longer allows for our custom HTML as it strips out <> characters. Returning formatting to the default INTL pattern.
Related issue: [VOL-5466](https://dvsa.atlassian.net/browse/VOL-5466)

fix: VOL-5466 compatibility with latest Laminas form

---

module/Olcs/src/Controller/Lva/Traits/ApplicationOverviewTrait.php
module/Olcs/src/Form/Model/Fieldset/ApplicationOverviewDetails.php

Adds "Application referred to PI" checkbox to overview.
Related issue: [VOL-5426](https://dvsa.atlassian.net/browse/VOL-5426)

feat: Application referred to pi checkbox vol 5426

---

.github/workflows/ci.yaml
.github/workflows/static-analysis.yaml

This fixes the CI workflow where Psalm now fails because PHP does not have Redis with IGBinary extension enabled (thus constant did not exist).
As a temporary measure, we copy-pasta the Static Analysis workflow from [dvsa/.github/workflows/php-static.yml](https://github.com/dvsa/.github/blob/main/.github/workflows/php-static.yml) and modify Setup PHP to compile Redis from source with support for IGBinary.
Related issue: https://dvsa.atlassian.net/browse/VOL-5559

fix: Psalm & Redis IGBinary issue

---

module/Olcs/view/layout/base.phtml
module/Olcs/view/layout/signin.phtml

Upgrade govuk-frontend to 5.x - requires loading new JS separately.
Related issue: [VOL-4716](https://dvsa.atlassian.net/browse/VOL-4716)

feat: Upgrade govuk frontend to 5.x
