dvsa/olcs-internal

composer.lock
=> feat: Bump olcs-transfer version

module/Olcs/src/Controller/Messages/LicenceCloseConversationController.php
fix: Close class refactor not picked up in Controller.
=> fix: Close class refactor not picked up in Controller.

module/Olcs/src/Controller/Factory/Messages/LicenceCloseConversationControllerFactory.php
Remove strong type from licence close factory.
=> fix: remove strong type from close factory

module/Admin/src/Form/Model/Fieldset/CpmsReportOptions.php
Related issue: [VOL-4853](https://dvsa.atlassian.net/browse/VOL-4853)
=> fix: remove invalid annotion from CPMS reports form

module/Olcs/src/Form/Model/Fieldset/TaskDetails.php
create task link on case processing notes was broken, now fixed
Related issue: [VOL-4854](https://dvsa.atlassian.net/browse/VOL-4854)
=> fix: VOL-4854 create task link on case processing notes is broken

composer.lock, module/Olcs/src/Form/Element/SearchDateRangeFieldsetFactory.php, module/Olcs/src/Form/Element/SearchFilterFieldsetFactory.php, module/Olcs/src/Form/Element/SearchOrderFieldsetFactory.php, module/Olcs/src/Module.php, test/Olcs/src/Form/Element/SearchOrderFieldsetFactoryTest.php
Fixes to Internal header search
Related issue: [VOL-4847](https://dvsa.atlassian.net/browse/VOL-4847)
=> fix: VOL-4687 internal header search fixes

module/Olcs/src/Table/Tables/conviction.table.php
=> fix: Fix a spelling mistake on Convictions empty table message.

module/Olcs/src/Controller/Cases/Processing/DecisionsController.php, module/Olcs/src/Controller/Cases/Processing/NoteController.php, module/Olcs/src/Controller/Cases/Processing/ReadHistoryController.php, module/Olcs/src/Controller/Cases/Processing/RevokeController.php, module/Olcs/view/sections/bus/partials/left.phtml, module/Olcs/view/sections/cases/partials/left.phtml, module/Olcs/view/sections/processing/partials/left.phtml
Fixes the case notes navigation issue plus several similar unreported issues
Related issue: [VOL-4849](https://dvsa.atlassian.net/browse/VOL-4849)
=> fix: various navigation issues fixed VOL-4849

module/Olcs/src/Controller/Messages/LicenceConversationMessagesController.php
On successful message reply, clear the textarea.
Related issue: [VOL-4530](https://dvsa.atlassian.net/browse/VOL-4530)
=> fix: On successful message reply, clear the textarea

module/Olcs/src/Controller/AbstractHistoryController.php
Fix controller using injected dependency incorrectly
Related issue: [VOL-4898](https://dvsa.atlassian.net/browse/VOL-4898)
=> fix: Broken factory wasn't instantiating one of its deps properly.

module/Admin/src/Controller/IrhpPermitRangeController.php, module/Admin/src/Form/Model/Fieldset/PermitRangeDetails.php, module/Admin/src/Form/Model/Fieldset/PermitStockDetails.php
Incorrect validation annotation, and added required inputFilter removal so forms validate as expected.
Related issue: [4901](https://dvsa.atlassian.net/browse/VOL-4901)
=> fix: Bad validator annotation, added needed conditional inputfilter removal.

module/Olcs/src/Controller/Messages/LicenceConversationMessagesController.php
After replying to a conversation, redirect to prevent re-submit
Related issue: [VOL-4905](https://dvsa.atlassian.net/browse/VOL-4905)
=> fix: After replying to a conversation, redirect to prevent re-submit

composer.json, composer.lock, module/Olcs/src/Form/Model/Fieldset/TmResponsibilities.php
and bump `olcs-common` to `5.0.0-beta.5`
Related issue: https://dvsa.atlassian.net/browse/VOL-4896 & https://dvsa.atlassian.net/browse/VOL-4894
=> fix: fix form ordering on TM responsibilities page

module/Olcs/src/Form/Model/Fieldset/DisableConversationsPopupText.php
Update the message disabling text to meet new AC.
Related issue: [VOL-4388](https://dvsa.atlassian.net/browse/VOL-4388)
=> feat: Change message disabling text to new AC

module/Olcs/src/Listener/RouteParam/Organisation.php, module/Olcs/view/sections/bus/partials/left.phtml, module/Olcs/view/sections/cases/partials/left.phtml, module/Olcs/view/sections/processing/partials/left.phtml, test/Olcs/src/Listener/RouteParam/OrganisationTest.php
Missed instances of `Navigation`.
=> fix: fix few missed `Navigation` changes

module/Admin/src/Controller/TeamControllerFactory.php, module/Olcs/src/Controller/Application/Processing/ApplicationProcessingInspectionRequestControllerFactory.php, module/Olcs/src/Controller/Factory/Operator/Cases/UnlicensedCasesOperatorControllerFactory.php, module/Olcs/src/Controller/Factory/Operator/HistoryControllerFactory.php, module/Olcs/src/Controller/Traits/FeesActionTrait.php
Set contentTitle to fees trait to set modal title correctly on any fee related modal windows.
Related issue: [VOL-4902](https://dvsa.atlassian.net/browse/VOL-4902)
=> fix: modal window headings fix for Fee related modals

module/Olcs/src/Table/Tables/piHearingReadOnly.table.php
Missed date constant.
Related issue: https://dvsa.atlassian.net/browse/VOL-4938
=> fix: resolve missing constant

module/Olcs/src/Controller/Factory/Licence/ContinuationControllerFactory.php
`Translator` -> `translator`
Related issue: https://dvsa.atlassian.net/browse/VOL-4945
=> fix: rename `Translator` to `translator` to fix missing factory

module/Olcs/src/Service/Data/AbstractPublicInquiryDataServicesFactory.php
=> fix: more dataservice fixes

module/Olcs/src/Controller/Factory/Licence/ContinuationControllerFactory.php
Add missing namespace.
Related issue: https://dvsa.atlassian.net/browse/VOL-4945
=> fix: add missing namespace

module/Admin/src/Form/Model/Fieldset/PermitsReportOptions.php
`Form\Label` does not exist.
Related issue: https://dvsa.atlassian.net/browse/VOL-4950
=> fix: remove unknown form annotation

test/Olcs/src/Listener/RouteParam/ConversationTest.php
Fix RouteParam test to include application changes.
Related issue: [VOL-4921](https://dvsa.atlassian.net/browse/VOL-4921)
=> fix: Update route param test for application routes

composer.lock, module/Olcs/config/module.config.php, module/Olcs/config/navigation-right-sidebar.config.php, module/Olcs/config/routes.config.php, module/Olcs/src/Controller/Factory/Messages/EnableDisableFileUploadControllerFactory.php, module/Olcs/src/Controller/Messages/EnableDisableFileUploadController.php, module/Olcs/src/Form/Model/Fieldset/DisableFileUploadPopupActions.php, module/Olcs/src/Form/Model/Fieldset/DisableFileUploadPopupText.php, module/Olcs/src/Form/Model/Fieldset/EnableFileUploadPopupActions.php, module/Olcs/src/Form/Model/Fieldset/EnableFileUploadPopupText.php, module/Olcs/src/Form/Model/Form/DisableFileUploadPopup.php, module/Olcs/src/Form/Model/Form/EnableFileUploadPopup.php, module/Olcs/src/Listener/RouteParam/Conversation.php, module/Olcs/view/pages/reload.phtml, test/Olcs/src/Listener/RouteParam/ConversationTest.php
Enable/disable file upload for messaging with upload functionality.
Related issue: [VOL-4393](https://dvsa.atlassian.net/browse/VOL-4393)
=> feat: Enable/Disable Messaging File Upload

composer.lock, module/Admin/src/Form/Model/Fieldset/FormSaveCancelPreview.php, module/Admin/src/Form/Model/Fieldset/TranslationKeyActions.php, module/Olcs/src/Controller/Cases/Submission/SubmissionController.php, module/Olcs/src/Controller/Cases/Submission/SubmissionControllerFactory.php, module/Olcs/src/FormService/Form/Lva/AbstractLvaFormFactory.php, module/Olcs/src/FormService/Form/Lva/ApplicationTypeOfLicence.php, module/Olcs/src/Table/Tables/operator-people.table.php, module/Olcs/view/sections/cases/pages/submission.phtml, test/Olcs/src/Mvc/Controller/Plugin/ConfirmTest.php
Limit the access of read only users to certain data and actions
Related issue: [VOL-5103](https://dvsa.atlassian.net/browse/VOL-5103)
=> fix: VOL-5103 limit the access of read only users to certain data and actions

module/Olcs/config/routes.config.php, module/Olcs/src/Controller/Messages/AbstractConversationMessagesController.php, module/Olcs/src/Controller/Messages/BusCloseConversationController.php, module/Olcs/src/Controller/Messages/BusEnableDisableMessagingController.php, module/Olcs/src/Controller/Messages/CaseEnableDisableMessagingController.php, module/Olcs/src/Controller/Messages/IrhpApplicationCloseConversationController.php, module/Olcs/src/Controller/Messages/IrhpApplicationEnableDisableMessagingController.php
Bus route was missing the licence/ prefix and the case route was using the wrong route parameter to get the organisation ID.
Related issue: [VOL-4692](https://dvsa.atlassian.net/browse/VOL-4692)
=> fix: Route parameters incorrect for new routes

composer.lock
Common and Utils packages bumped to the latest
=> chore: bump common and utils packages

module/Olcs/src/Form/Model/Fieldset/CloseConversationText.php
Use translations in close popup.
Related issue: [VOL-5121](https://dvsa.atlassian.net/browse/VOL-5121)
=> feat: Use translation key in close popup

module/Olcs/src/Controller/IndexController.php
On search page, allow viewing all messages across all teams
Related issue: [VOL-5124](https://dvsa.atlassian.net/browse/VOL-5124)
=> feat: Allow searching for all messages

config/autoload/config-paramater.global.php
Tweaks the secret name template for config. This is messy and will be cleaned in the migration to ECS.
=> fix: tweak secret template to work for production

module/Olcs/src/Controller/Messages/CaseCreateConversationController.php
Link application to case created conversation.
Related issue: [VOL-5093](https://dvsa.atlassian.net/browse/VOL-5093)
=> fix: Case created conversation not linked to app

module/Olcs/src/Form/Model/Fieldset/Conversation.php, module/Olcs/src/Form/Model/Fieldset/LicenceMessageReply.php
Custom error texts for Messaging forms
Related issue: [VOL-5003](https://dvsa.atlassian.net/browse/VOL-5003)
=> feature: Messaging command validation

composer.lock, module/Olcs/src/Controller/Messages/AbstractConversationListController.php, module/Olcs/src/Form/Model/Form/ConversationFilter.php, module/Olcs/view/partials/vertical-message-navigation.phtml
Allow filtering conversations by status.
Related issue: [VOL-4650](https://dvsa.atlassian.net/browse/VOL-4650)
=> feat: Allow conversation status filtering

composer.lock, module/Olcs/src/Controller/Document/DocumentGenerationController.php, module/Olcs/src/Controller/Document/DocumentUploadController.php
Unable to generate or upload new document
Related issue: [VOL-5189](https://dvsa.atlassian.net/browse/VOL-5189)
=> fix: Unable to create or upload new document

composer.lock
=> chore: bump olcs-common to 6.7.6

module/Olcs/src/Controller/Operator/OperatorIrfoGvPermitsController.php, module/Olcs/src/Controller/Operator/OperatorIrfoGvPermitsControllerFactory.php, module/Olcs/view/sections/operator/pages/irfo-gv-permit.phtml
Read only users now don't get the action buttons for irfo gv permits
Related issue: [VOL-5226](https://dvsa.atlassian.net/browse/VOL-5226)
=> fix: VOL-5226 irfo gv permits now locked down for read only users

composer.json, composer.lock, module/Olcs/src/Controller/Traits/FeesActionTrait.php
Reverts dvsa/olcs-internal#155
=> chore: revert "fix: Only show valid fees for licences"

config/autoload/config.global.php, config/autoload/local.php.dist
Check the environment variables for an `APP_VERSION`. This is how the application will get it's version once migrated to ECS.
=> feat: check version in environment variable

module/Olcs/view/sections/cases/pages/print-submission.phtml, module/Olcs/view/sections/cases/pages/submission.phtml
Fix some bugs passing null to array_column()
Related issue: [VOL-5438](https://dvsa.atlassian.net/browse/VOL-5438)
=> fix: fix some bugs passing null to array_column

module/Admin/src/Form/Model/Fieldset/FeeRateDetails.php, module/Admin/src/Form/Model/Fieldset/UserLoginSecurity.php, module/Olcs/src/Form/Model/Fieldset/CreatePermit.php, module/Olcs/src/Form/Model/Fieldset/IrhpApplication/Top.php, module/Olcs/src/Form/Model/Fieldset/IrhpBilateral/Top.php, module/Olcs/src/Form/Model/Fieldset/OperatorId.php, module/Olcs/src/Form/Model/Fieldset/TransportManagerDetails.php, module/Olcs/view/sections/fees/pages/fee-details.phtml, module/Olcs/view/sections/fees/pages/transaction-details.phtml
Fixes ReadonlyElement rename, and some static calls to non-static methods.
Related issue: [VOL-5436](https://dvsa.atlassian.net/browse/VOL-5436)
Related issue: [VOL-5435](https://dvsa.atlassian.net/browse/VOL-5435)
=> fix: Internal edit fees page error vol 5436

config/autoload/config.global.php
=> feat: add CDN support

composer.json, composer.lock
Bump dependency to bring in fixes on latest builds
=> fix: bump common to include recent fixes

module/Admin/src/Controller/MyDetailsController.php, module/Admin/src/Controller/UserManagementController.php, module/Admin/src/Form/Model/Fieldset/UserSettings.php, module/Olcs/src/Controller/Document/AbstractDocumentController.php, module/Olcs/src/Data/Mapper/User.php, test/Olcs/src/Data/Mapper/UserTest.php
Docman support has been removed from the app
Related issue: [VOL-4635](https://dvsa.atlassian.net/browse/VOL-4635)
=> feat: VOL-4635 remove docman support

composer.json, composer.lock, module/Admin/config/module.config.php, module/Admin/config/navigation.config.php, module/Admin/src/Controller/LocalAuthorityController.php, module/Admin/src/Controller/LocalAuthorityControllerFactory.php, module/Admin/src/Data/Mapper/LocalAuthority.php, module/Admin/src/Form/Model/Fieldset/LocalAuthorityDetails.php, module/Admin/src/Form/Model/Form/LocalAuthority.php, module/Admin/src/Table/Tables/admin-local-authority.table.php, module/Admin/view/pages/local-authority/index.phtml
Local Authority Admin Edit Functionality
Related issue: [VOL-5532](https://dvsa.atlassian.net/browse/VOL-5532)
=> feat: LTA Admin edit functionality

config/autoload/config.global.php
As title.
Context is that we're logging a lot of information at the moment and missing vital parts.
=> feat: change log level to `WARN`

composer.json, composer.lock
Upgrade min olcs-common version
=> feat: Upgrade olcs-common to ^7.6.0
